### ISSUE TITLE
Unable to set tiers (Python n00b)

### ISSUE THREAD

**Issue by UltraHKR** [Tomodoro/qbitseedmgr#3]
Host: Debian 13 trixie/sid (autoupdated)
qbittorrent-nox/testing,now 4.6.3-1 amd64 (from Debian APT)

Steps to install:
git clone https://github.com/Tomodoro/qbitseedmgr.git
sudo apt install python3-venv python3-pip
cd qbitseedmgr/
python3 -m venv ./
nano qbitseedmgr.ini (edit user/pass, ip:port)
qbtuser@qb:~/qbitseedmgr$ ./bin/pip3 install qbittorrent-api

```
Collecting qbittorrent-api
  Downloading qbittorrent_api-2024.1.58-py3-none-any.whl.metadata (18 kB)
Collecting requests>=2.16.0 (from qbittorrent-api)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting urllib3>=1.24.2 (from qbittorrent-api)
  Downloading urllib3-2.2.0-py3-none-any.whl.metadata (6.4 kB)
Collecting packaging (from qbittorrent-api)
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.16.0->qbittorrent-api)
  Downloading charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests>=2.16.0->qbittorrent-api)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting certifi>=2017.4.17 (from requests>=2.16.0->qbittorrent-api)
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
..............
Installing collected packages: urllib3, packaging, idna, charset-normalizer, certifi, requests, qbittorrent-api
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.6 packaging-23.2 qbittorrent-api-2024.1.58 requests-2.31.0 urllib3-2.2.0
```

qbtuser@qb:~/qbitseedmgr$ ./bin/python qbitseedmgr.py set-tiers

```
INFO: Sucessful login with credentials
Traceback (most recent call last):
  File "/home/qbtuser/qbitseedmgr/qbitseedmgr.py", line 193, in <module>
    set_tiers()
  File "/home/qbtuser/qbitseedmgr/qbitseedmgr.py", line 117, in set_tiers
    client.torrents_set_share_limits(config["Tier 0"]["ratio_limit"],config["Tier 0"]["seeding_time_limit"], config["Tier 0"]["inactive_seeding_time_limit"], torrent_hashes=hash)
                                                                                                             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/configparser.py", line 1273, in __getitem__
    raise KeyError(key)
KeyError: 'inactive_seeding_time_limit'
```

**Comment by UltraHKR** [comment]
Do note that the first tier "@tier0" is successfully created.

**Comment by Tomodoro** [comment]
Hello @UltraHKR,

Thank you for your report. Checking the diff I see my mistake. The key is `seeding_time_limit`, but in #2 I used `inactive_seeding_time_limit`.

Seeing the order of the code, the tag for tier0 was created correctly because it happens before the code attempts to read the wrong key (the torrent should not have changed its limits because of this).

I ran sed to change the wrong key name. Making `git pull` on your local copy should bring the fix to your machine.

**Comment by UltraHKR** [comment]
Hello Tomodoro

I'm happy to report it's fixed, thank you.

**Comment by UltraHKR** [comment]
config file, just in case:
```
qbtuser@qb-pornz2:~$ cat ./qbitseedmgr/qbitseedmgr.ini
[Client]
host = w.x.y.z
port = 8080
credentials = True
username = someuser
password = password

# max_num_seeds – will pause the torrent if seeds are above this value and will resume the torrent if below this value
# min_ratio – will pause the torrent if ratio is above this value (set 0 to only count max_num_seeds)

[Not popular]
max_num_seeds = 10
min_ratio = 2
# tag_exception = Software

# ratio_limit – max ratio to seed a torrent. (-2 means use the global value and -1 is no limit)
# seeding_time_limit – minutes (-2 means use the global value and -1 is no limit)
# upload_limit – bytes/second (-1 sets the limit to infinity)

[Tier free]
ratio_limit = -1
seeding_time_limit = -1
upload_limit = -1

[Tier 0]
ratio_limit = 5
seeding_time_limit = -2
upload_limit = -1

[Tier 1]
ratio_limit = 10
seeding_time_limit = -2
upload_limit = 460800

[Tier 2]
ratio_limit = 15
seeding_time_limit = -2
upload_limit = 409600

[Tier 3]
ratio_limit = 20
seeding_time_limit = -2
upload_limit = 358400

[Tier 4]
ratio_limit = 25
seeding_time_limit = -2
upload_limit = 307200

[Tier 5]
ratio_limit = 30
seeding_time_limit = -2
upload_limit = 256000

[Tier 6]
ratio_limit = 35
seeding_time_limit = -2
upload_limit = 204800

[Tier 7]
ratio_limit = 40
seeding_time_limit = -2
upload_limit = 153600

[Tier 8]
ratio_limit = 45
seeding_time_limit = -2
upload_limit = 102400

[Tier 9]
ratio_limit = 50
seeding_time_limit = -2
upload_limit = 51200
```

**Comment by UltraHKR** [comment]
I got why it's failing, I compared the repo file against my local config

If I comment this line it fails:
# tag_exception = Software

But if I let it as is, without touching it even if that category does not exist in my qb instance, it works...

So I would say it's fixed, just add a warning to keep it (as is) or set that line to a proper value if needed.

**Comment by Tomodoro** [comment]
What happens is that `qbitseedmgr.py` has hardcoded all the keys from `qbitseedmgr.ini`. If you use the program as is, you will have a reasonable bandwidth throttler. You can change the key's values, but if there is something you want to add or remove you'll have to edit `qbitseedmgr.py`.

The code is just a series of if/else statement so anyone can adjust it to their needs. As a downside, it lacks the proper sanity checks and warnings you'll expect from a full program.

> But then trying this, it fails...:
> 
> ```
> qbtuser@qb:~/qbitseedmgr$ ./bin/python qbitseedmgr.py not-popular
> INFO: Sucessful login with credentials
> Traceback (most recent call last):
>   File "/home/qbtuser/qbitseedmgr/qbitseedmgr.py", line 199, in <module>
>     not_popular()
>   File "/home/qbtuser/qbitseedmgr/qbitseedmgr.py", line 82, in not_popular
>     is_exception = re.search(config["Not popular"]["tag_exception"],tags)
>                              ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/configparser.py", line 1273, in __getitem__
>     raise KeyError(key)
> KeyError: 'tag_exception'
> ```

[This line](https://github.com/Tomodoro/qbitseedmgr/blob/a966583e6ba69c6552f4842dcf17a81fd32069d6/qbitseedmgr.py#L82) is what generates your new error because it tries to read the key `tag_exception`, and since you had it commented it fails. Deleting that line and the subsequent conditional check will remove the behavior.

I hope this fixes your issue and clarifies how does the tool work.

**Comment by Tomodoro** [comment]
Closing as solved.
